spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://foodfixdatabase.cjwagiym2fr4.ap-northeast-2.rds.amazonaws.com:3306/foodfixdatabase?serverTimezone=UTC&characterEncoding=UTF-8
    username: minjun0307
    password: admin123!
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  session:
    store-type: none
  security:
    jwt:
      token:
        secret-key: secretKey
        expire-length: 3600000
